MemBlock would be treated as direct base class
which is not. g++ 4.6.3 showes following compile error message
```
src/structure.h: In constructor ‘bible::MemBlock::MemBlock()’:
src/structure.h:49:15: error: type ‘bible::MemBlock’ is not a direct base of ‘bible::MemBlock’
```